[package]
name = "coven"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
dioxus-router = "0.4.1"
dioxus-signals = { git = "https://github.com/DioxusLabs/dioxus" }
dirs = "5.0.1"
nest = "1.0.0"
quic-rpc = { version = "0.6.1", features = ["flume-transport"] }
